version: "3"
services:
  server:
    container_name: fuquizserver
    build: ./FuQuiz-BE
    image: dauleduc2/fuquizserver:latest
    ports:
      - 4000:4000
    networks:
      - tetcha
  client:
    container_name: fuquizclient
    build: ./FuQuiz-FE
    image: dauleduc2/fuquizclient:latest
    ports:
      - 3000:3000
    networks:
      - tetcha
networks:
  tetcha:
    external: true
