name: Docker Image CI

on:
  push:
    branches: [deploy]
jobs:
   BuildAndPush:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name : run command code to add .env file and push to server
      run: |
            ls
  #     run: |
  #          cd ./frontend
  #          echo "REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }}" > .env.production
  #          cd ../
  #          cd ./backend
  #          mkdir config
  #          cd ./config
  #          echo "DB_HOST=${{ secrets.DB_HOST }}
  #                DB_PORT=${{ secrets.DB_PORT }}
  #                DB_USERNAME=${{ secrets.DB_USERNAME }}
  #                DB_PASSWORD=${{ secrets.DB_PASSWORD }}
  #                DB_NAME=${{ secrets.DB_NAME }}
  #                WT_SECRET=${{ secrets.JWT_SECRET }}
  #                PORT=${{ secrets.SERVER_PORT }}
  #                CLIENT_URL=${{ secrets.CLIENT_URL }}
  #                REDIS_PORT=${{ secrets.REDIS_PORT }}
  #                REDIS_DB_NUMBER=${{ secrets.REDIS_DB_NUMBER }}
  #                REDIS_HOST=${{ secrets.REDIS_HOST }}" > .env.production
  #   - name: Build on docker-compose file
  #     run: |
  #          docker-compose -f docker-compose.github.yml build
  #   - name: login to docker hub
  #     uses: docker/login-action@v1
  #     with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #   - name: push frontend to dockerhub
  #     run: |
  #          docker push dauleduc2/datingappweb:latest
  #   - name: push server to dockerhub
  #     run: |
  #          docker push dauleduc2/datingappserver:latest
  #  deploy:
  #   runs-on: ubuntu-latest
  #   needs: [BuildAndPush]
  #   steps:
  #     - name: executing remote ssh commands using ssh key
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         password: ${{ secrets.PASSWORD }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #                 cd /app/Dating-app
  #                 docker-compose pull
  #                 docker-compose up -d
  #                 echo done